#!/usr/bin/env python3
"""
generate_changelog.py - Generate a structured CHANGELOG.md from git history.

Supports two modes:
1. Git-based: Uses local git log (requires Git installed)
2. API-based: Uses GitHub API to fetch commits (no git required)

Usage:
    python generate_changelog.py --repo OWNER/REPO [--since-tag TAG] [--output FILE]
    python generate_changelog.py --git-path PATH [--since-tag TAG] [--output FILE]
"""

import argparse
import json
import os
import re
import subprocess
import sys
import urllib.request
from collections import OrderedDict
from datetime import datetime


CATEGORY_MAP = {
    'feat': 'Added', 'feature': 'Added', 'new': 'Added', 'add': 'Added',
    'fix': 'Fixed', 'bugfix': 'Fixed', 'bug': 'Fixed',
    'perf': 'Performance', 'performance': 'Performance',
    'refactor': 'Changed', 'change': 'Changed', 'update': 'Changed',
    'chore': 'Changed', 'docs': 'Changed', 'documentation': 'Changed',
    'style': 'Changed', 'build': 'Changed', 'ci': 'Changed', 'test': 'Changed',
    'remove': 'Removed', 'delete': 'Removed', 'rm': 'Removed',
    'security': 'Security', 'vuln': 'Security', 'deps': 'Changed',
    'release': 'Changed',
}


def fetch_commits_via_api(repo, since_tag=None):
    """Fetch commits via GitHub API."""
    url = f'https://api.github.com/repos/{repo}/commits?per_page=100'
    if since_tag:
        url += f'&sha={since_tag}'

    headers = {
        'Accept': 'application/vnd.github.v3+json',
        'User-Agent': 'CHANGELOG-Generator/1.0',
    }

    token = os.environ.get('GITHUB_TOKEN')
    if token:
        headers['Authorization'] = f'token {token}'

    req = urllib.request.Request(url, headers=headers)
    with urllib.request.urlopen(req, timeout=30) as resp:
        raw = json.loads(resp.read().decode())
        commits = []
        for c in raw:
            msg = c['commit']['message'].split('\n')[0]
            commits.append({'sha': c['sha'][:8], 'message': msg})
        return commits


def fetch_commits_via_git(repo_path, since_tag=None):
    """Fetch commits via local git log."""
    cmd = ['git', 'log', '--pretty=format:%H|||%s', '--no-merges']
    if since_tag:
        cmd.insert(3, f'{since_tag}..HEAD')

    result = subprocess.run(cmd, cwd=repo_path, capture_output=True, text=True, timeout=30)
    if result.returncode != 0:
        return []

    commits = []
    for line in result.stdout.strip().split('\n'):
        if not line:
            continue
        parts = line.split('|||', 1)
        if len(parts) == 2:
            commits.append({'sha': parts[0][:8], 'message': parts[1]})
    return commits


def parse_commit(message):
    """Parse conventional commit message into type, scope, description."""
    match = re.match(r'^(\w+)(?:\(([^)]*)\))?\s*:\s*(.+)$', message)
    if match:
        return match.group(1).lower(), match.group(2) or '', match.group(3).strip()
    return None, '', message


def categorize_commits(commits):
    """Group commits by category."""
    categories = OrderedDict()
    for cat in ['Added', 'Fixed', 'Changed', 'Removed', 'Performance', 'Security']:
        categories[cat] = []

    for commit in commits:
        msg = commit['message']
        sha = commit['sha']
        commit_type, scope, description = parse_commit(msg)

        if commit_type and commit_type in CATEGORY_MAP:
            category = CATEGORY_MAP[commit_type]
        else:
            category = 'Changed'

        clean_desc = description.capitalize() if description else msg.capitalize()
        scope_str = f' **`{scope}`**' if scope else ''

        categories[category].append({
            'message': msg,
            'sha': sha,
            'clean_desc': clean_desc,
            'scope_str': scope_str,
        })

    return categories


def generate_markdown(categories, repo_name='', version=''):
    """Generate the CHANGELOG markdown content."""
    lines = []
    header = '# CHANGELOG'
    if version:
        header += f' - v{version}'
    elif repo_name:
        header += f' - {repo_name}'
    lines.append(header)
    lines.append('')
    lines.append(f'*Generated on {datetime.now().strftime("%Y-%m-%d %H:%M")}*')
    lines.append('')
    lines.append('---')
    lines.append('')

    has_content = False
    for category, items in categories.items():
        if not items:
            continue
        has_content = True
        lines.append(f'## {category}')
        lines.append('')
        for item in items:
            lines.append(f'- {item["clean_desc"]}{item["scope_str"]} (`{item["sha"]}`)')
        lines.append('')

    if not has_content:
        lines.append('*No changes recorded.*')
        lines.append('')

    lines.append('---')
    lines.append('')
    lines.append('*This changelog was auto-generated by generate_changelog.py.*')
    lines.append('')

    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description='Generate CHANGELOG from git history')
    parser.add_argument('--repo', '-r', help='GitHub repo (OWNER/REPO) for API mode')
    parser.add_argument('--git-path', '-p', help='Local git repo path for git mode')
    parser.add_argument('--since-tag', '-s', help='Generate since this tag')
    parser.add_argument('--output', '-o', default='CHANGELOG.md', help='Output file')
    parser.add_argument('--version', '-v', help='Version string for header')
    parser.add_argument('--quiet', action='store_true', help='Suppress stdout')
    args = parser.parse_args()

    commits = []

    if args.repo:
        print(f'Fetching commits from {args.repo}...', file=sys.stderr)
        try:
            commits = fetch_commits_via_api(args.repo, args.since_tag)
            print(f'Fetched {len(commits)} commit(s).', file=sys.stderr)
        except Exception as e:
            print(f'API fetch failed: {e}', file=sys.stderr)
            sys.exit(1)
    elif args.git_path:
        print(f'Scanning git repo: {args.git_path}', file=sys.stderr)
        try:
            commits = fetch_commits_via_git(args.git_path, args.since_tag)
            print(f'Found {len(commits)} commit(s).', file=sys.stderr)
        except Exception as e:
            print(f'Git scan failed: {e}', file=sys.stderr)
            sys.exit(1)
    else:
        print('Scanning current directory for git repo...', file=sys.stderr)
        try:
            commits = fetch_commits_via_git('.', args.since_tag)
        except Exception:
            print('No git repo found. Use --repo OWNER/REPO for API mode.', file=sys.stderr)
            sys.exit(1)

    if not commits:
        print('No commits found.', file=sys.stderr)
        categories = OrderedDict([
            ('Added', []), ('Fixed', []), ('Changed', []),
            ('Removed', []), ('Performance', []), ('Security', []),
        ])
    else:
        categories = categorize_commits(commits)

    changelog = generate_markdown(categories, args.repo, args.version)

    output_dir = os.path.dirname(args.output)
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)

    with open(args.output, 'w', encoding='utf-8') as f:
        f.write(changelog)

    if not args.quiet:
        print(changelog)

    print(f'\nChangelog written to: {args.output}', file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
